export interface baseEvent{ 
    event: string,
    data: any,
}

export enum Events { 
    // events from server to clients
    CLIENT_CONNECTED = 'CLIENT_CONNECTED',
    GAME_UPDATE = 'GAME_UPDATE',
    SERVER_SHUTDOWN = 'SERVER_SHUTDOWN',
    GAME_OVER = 'GAME_OVER',
    GAMES_FULL = 'GAMES_FULL',
    PLAYER_CONNECTED = 'PLAYER_CONNECTED',
    GAME_CREATED = 'GAME_CREATED',
    NAME_NOT_UNIQUE = 'NAME_NOT_UNIQUE',
    GAME_LIMIT_REACHED = 'GAME_LIMIT_REACHED',
    GAME_LIST = 'GAME_LIST',
    SPECTATE_LIST = 'SPECTATE_LIST',
    
    // events from clients to server
    UPDATE_GAME = 'UPDATE_GAME',
    CREATE_GAME = 'CREATE_GAME',
    SPECTATE_GAME_REQUEST = 'SPECTATE_GAME_REQUEST',
    SPECTATE_GAME = 'SPECTATE_GAME',
    JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST',
    JOIN_GAME = 'JOIN_GAME',
    PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
}